spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/backoffice}
    username: ${DB_USERNAME:backoffice}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false